### ISSUE TITLE
Make a plan for the REST API to interact with the backend

### ISSUE THREAD

**Issue by salekd** [AstroPlant/astroplant-backend#16]
1. Choose the technology.

I have experience with Flask-RESTPlus https://flask-restplus.readthedocs.io/en/stable/

There are other options, e.g. https://github.com/zalando/connexion

2. Which endpoints do we want to implement in the first version?

**Comment by salekd** [comment]
We will start with Flask, although there are concerns about the change of the maintainer. @Beskhue could you please share more details on this?

In any case, I will provide a skeleton with endpoints related to the kits and aggregate measurements.

We need to investigate what to do about the authentication.

**Comment by salekd** [comment]
Going forward with Rust.

@Beskhue could you please provide a list of endpoints/required functionality you intend to implement in the initial version?

**Comment by tomcur** [comment]
The API is being documented here:

https://github.com/AstroPlant/astroplant-api/blob/6a106239efd284c14877b30b2e39a47a41aa1e3d/openapi.yaml

I'm not sure yet about the exact endpoints, esp. related to measurements and configurations, but currently there's:

* \* - indicates the endpoint requires the request to be authenticated
* \** - indicates the endpoint might require the request to be authenticated

| Endpoint | Description |
| ----------- | -------------- |
| `GET /kits` | List all public kits. |
| `POST /kits` | * Create a kit. |
| `GET /kits/{kitId}` | ** Info for a specific kit. |
| `POST /users` | Create a user. |
| `GET /me` | * Your user information. |
| `GET /me/memberships` | * Your kit memberships. |
| `POST /me/auth` | Authenticate yourself by username and password (returns a normal token and a refresh token). |
| `POST /me/refresh` | Obtain a normal token from a refresh token. |

And we minimally require something like:

| Endpoint | Description |
| ----------- | -------------- |
| `GET /kits/{kitId}/measurements` | ** Get all measurements made by the kit (with some query parameters for filtering). |
| `GET /kits/{kitId}/rawMeasurements` | ** Get all raw (non-aggregated) measurements made by the kit (with some query parameters for filtering). |
| `GET /kits{kitId}/configurations` | ** Get all configurations of the kit (all inactive configurations and the active configuration). |
| `POST /kits/{kitId}/configurations` | * Create a new configuration for the kit. |
| `GET /kits/{kitId}/activeConfiguration` | ** Get the currently active configuration for the kit. |
| `PUT /kits/{kitId}/activeConfiguration` | * Set the currently active configuration for the kit (first created through `POST /kits/{kitId}/configurations`). |
| `GET /kits/{kitId}/memberships` | * Get the kit memberships. |
| `POST /kits/{kitId}/memberships` | * Create a kit membership. |
| `PUT /kits/{kitId}/memberships/{membershipId}` | * Update the kit membership. |

Probably we also want some delete endpoints:

| Endpoint | Description |
| ----------- | --------------- |
| `DELETE /users/{userId}` | * Delete a user. |
| `DELETE /kits/{kitId}` | * Delete the kit. |
| `DELETE /kits/{kitId}/configurations/{configurationId}` | * Delete the kit configuration. |
| `DELETE /kits/{kitId}/memberships/{membershipId}` | * Delete the kit membership. |
| `DELETE /kits/{kitId}/memberships/{membershipId}` | * Delete the kit membership. |

For discovery of users one can add a membership to their kit for, we might need the following (but we have to think about privacy, such as requiring the email address to be known, and/or only producing a list of usernames):

| Endpoint | Description |
| ----------- | --------------- |
| `GET /users?maybeSomeFilter` | * A list of users. |

Any thoughts? Some specific things we need to think about:

1. Should we choose nested or flat resources (`/kits/{kitId}/measurements` vs `/measurements?kitId={kitId}`)? I'm leaning towards nested (but not nested too deply), to have the difference between things like `/me/memberships` and `/kits/{kitId}/memberships` be very clear.
1. Do we need endpoints to delete measurements?
1. Do we need endpoints for adding measurements manually?
1. There's no support for updating an existing kit configuration, as it'd mess with measurements already linked to it. How do we ensure new configurations can be made easily (or is this purely a front-end issue)? Think about what happens when the user's browser crashes in the middle of creating a complex configuration.

**Comment by thiemehennis** [comment]
thanks Thomas! And interesting questions

my 2 cents on q 4; is it possible to have fallback configurations for each kit? is that useful?

**Comment by tomcur** [comment]
@thiemehennis To my mind, the most important is that measurements should always be traceable to the exact configuration under which the measurement was made. If a specific configuration can be mutated, then when the user does so the exact configuration information is no longer available for old measurements linked to that configuration.

Perhaps the solution is to allow configurations to be updated if and only if they've never been activated yet? A front-end can then warn the user when they go to activate a new configuration: "Once you activate this configuration, you can no longer make changes to it. You will need to create a new configuration to make changes."

Front-ends could also provide some functionality to clone an existing configuration.

**Comment by thiemehennis** [comment]
so every configuration should have a unique identifier right? and all data
per kit is then linked to that identifier, and the identifier is linked to
the specific configuration?

**Comment by tomcur** [comment]
@thiemehennis Indeed: each kit can have many configurations, and each kit as well as each configuration is uniquely identifiable. Configurations uniquely belong to a specific kit. A kit can have _only one_ active configuration at any one time. All measurements are linked to a specific configuration.

**Comment by tomcur** [comment]
This is now in place at https://github.com/AstroPlant/astroplant-api (though the specific choices of API endpoints are still being iterated).
