### ISSUE TITLE
Fix class name for virtual barometer

### ISSUE THREAD

**Issue by salekd** [AstroPlant/astroplant-backend#33]
This does not look right.
https://github.com/AstroPlant/astroplant-backend/blob/6c285624b1a4e0224e674c968dd59c94969cfc72/kafka-db-connector/connector/database.py#L553

```
            class_name = 'Temperature',
            quantity_types=[
                qt_temperature,
                qt_pressure,
                qt_humidity,
            ],
```

What is the class name for?

**Comment by tomcur** [comment]
Fixed in 3e94717548ad54319d40790bece03ee3339b69f8.

The module name and class name together identify the implementation the kit has to load to run the peripheral. For example, module name `astroplant_simulation.sensors` with class name `barometer` refers to https://github.com/AstroPlant/astroplant-simulation/blob/14b5a899ce4044256f59b0544b4436eae753a5bd/astroplant_simulation/sensors.py#L38
