### ISSUE TITLE
Revisit the message format validation

### ISSUE THREAD

**Issue by salekd** [AstroPlant/astroplant-backend#7]
- The AVRO message format is checked automatically when producing to Kafka. Should we do the validation in the producer code beforehand (in case a wrong schema is attached to a topic on the Kafka side)?
- Should we check the JSON format before publishing messages to MQTT?

**Comment by salekd** [comment]
We chose to get rid of the Schema registry. Therefore, the Avro format needs to be checked at the application level. It is important to check it both on the kit side and the backend side (there might be different versions in place on both sides).

We agreed to send messages in the Avro format over MQTT as well.

**Comment by tomcur** [comment]
See commits b58824c74ba5189fdafcd7712338f6b8da39eaca and 03521231a2489f50b1c42a1aff6fb18f5cd04206.

Avro schema adherence is now implicitly checked through `fastavro`, due to it being used to encode and decode messages explicitly. The schemas are shipped with the code, and no longer fetched from a registry. The MQTT API assumes kits send messages in Avro format.
